### ISSUE TITLE
OpenAI API - API Key Rotates when I coomit to GitHub

### ISSUE THREAD

**Issue by tynoschuck** [adrianhajdin/project_ai_mern_image_generation#10]
Hello there!
I'm trying to commit the project to GitHub, but everytime I receive the mail fro openAI telling me that they rotated the key because it got exposed.
I already created the .gitignore file with .env, but it does not seems to work. I do not have the .env file in my repository https://github.com/tynoschuck/Ai-image-generator but I keep receiving the mail.
Any chande you know how to fix this? Thanks in advance!

**Comment by kevmhughes** [comment]
Hey! Did you find a solution in the end?

**Comment by minal322** [comment]
Did you find any solution for the same
