### ISSUE TITLE
SyntaxError: Unexpected token 'B', "Billing ha"... is not valid JSON

### ISSUE THREAD

**Issue by iamutkarshyadav** [adrianhajdin/project_ai_mern_image_generation#32]
![Screenshot 2023-02-18 215930](https://user-images.githubusercontent.com/72760223/219877012-bc5e3c51-0c85-4286-a003-5b40df1d5aaf.png)

**Comment by binyamdawit** [comment]
Hey @iamutkarshyadav I think I might have the solution for that!

in your CreatePost.jsx file under the generateImage function. Change your fetch response to => const response = await fetch('http://localhost:8080/api/v1/dalle', {
Hope that helps.

**Comment by binyamdawit** [comment]
And if that works, I suggest you do the same thing for all the other ones. Such as for the fetch response: https://dalle-arbb.onrender.com/api/v1/post, change it to => http://localhost:8080/api/v1/post

**Comment by iamutkarshyadav** [comment]
thanks, it worked!
