### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by soumizde** [adrianhajdin/project_ai_mern_image_generation#55]
![Screenshot (92)](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/104732379/5c286d55-1f10-4252-ab48-e03c029267b1)

As soon as I am inputting 
 const response = await fetch("https://dalle-arbb.onrender.com/api/v1/post", {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        });
I am getting a CORS error. How do I fix this?

**Comment by adnan179** [comment]
use the url "http://localhost:8080/api/v1/post"
as it is the url u are using to fetch data as of now, which is from the server

**Comment by soumizde** [comment]
I tried that and I even tried removing the http://localhost:8080 which may sometimes resolve the error. Now I am not getting a CORS error however I still cannot fetch the data
