### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by strangertomycode** [adrianhajdin/project_ai_mern_image_generation#75]
I am unable to generate image. Every time I try to generate an image the following error is showing:

![Screenshot from 2024-04-07 07-47-39](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/114813900/a23c6a08-cfe2-4438-9716-99ae23938067)

Error:
Access to fetch at 'https://dalle-arbb.onrender.com/api/v1/dalle' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
CreatePost.jsx:31 
        
        
POST https://dalle-arbb.onrender.com/api/v1/dalle net::ERR_FAILED
       
       
Can anyone please help me?

**Comment by ItsAnkitPatel** [comment]
Hey @sreeram3015 Is your code publically available ? My project working fine (did some changes because the code provided in the yt video is old) let me know I will try to check out what's the issue.

**Comment by Archana2806** [comment]
> Hey @sreeram3015 Is your code publically available ? My project working fine (did some changes because the code provided in the yt video is old) let me know I will try to check out what's the issue.

Can you share what you have changed in the code which resolved the issue. I too am facing the problem while generating a picture.

**Comment by ItsAnkitPatel** [comment]
> Can you share what you have changed in the code which resolved the issue. I too am facing the problem while generating a picture.

Well I updated many parts of the code which I can't recall right now
This is my [repo link](https://github.com/ItsAnkitPatel/DALL-E)
without checking side by side I can't tell which part I changed sorry for that.
One change I remember is I changed the **OpenAI API call** code in `server/routes/dalleRoute.js`

https://github.com/ItsAnkitPatel/DALL-E/blob/304b68a98e21c0cb4ae84aa8f9792f9695eaef19/server/routes/dalleRoutes.js#L20

**Comment by Archana2806** [comment]
> > Can you share what you have changed in the code which resolved the issue. I too am facing the problem while generating a picture.
> 
> Well I updated many parts of the code which I can't recall right now This is my [repo link](https://github.com/ItsAnkitPatel/DALL-E) without checking side by side I can't tell which part I changed sorry for that. One change I remember is I changed the **OpenAI API call** code in `server/routes/dalleRoute.js`
> 
> https://github.com/ItsAnkitPatel/DALL-E/blob/304b68a98e21c0cb4ae84aa8f9792f9695eaef19/server/routes/dalleRoutes.js#L20

i think i made some blunder and might need your help, where can i reach you

**Comment by ItsAnkitPatel** [comment]
> i think i made some blunder and might need your help, where can i reach you

I see, can you share your repo ? I will try to look into it too.
And I am available at discord 
Discord username: `ankit_patel`

**Comment by Archana2806** [comment]
> > i think i made some blunder and might need your help, where can i reach you
> 
> I see, can you share your repo ? I will try to look into it too. And I am available at discord Discord username: `ankit_patel

Texted you

**Comment by Rutuja1427** [comment]
I am also facing same ptoblem

**Comment by ItsAnkitPatel** [comment]
> I am also facing same ptoblem

Can you share your code repo?

**Comment by akshay2245** [comment]
bro i m also facing a problem i have downloaded your version of code and i have checked but i m getting "api limit reached error"

**Comment by ItsAnkitPatel** [comment]
> bro i m also facing a problem i have downloaded your version of code and i have checked but i m getting "api limit reached error"
> 
> 
> 
> 

Well that only happens when the user sent the too long prompt or the api is expired.

Are you using your own API key ?

**Comment by akshay2245** [comment]
yes i m using my own api that all i did and prompt was made using that surprise me button

**Comment by akshay2245** [comment]
<img width="1470" alt="Screenshot 2024-04-12 at 1 20 05 AM" src="https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/83343001/b0dbc439-99ab-4e42-99e6-9183c44e365e">
bro do i need to buy subscription to use the feature?

**Comment by ItsAnkitPatel** [comment]
> <img width="1470" alt="Screenshot 2024-04-12 at 1 20 05 AM" src="https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/83343001/b0dbc439-99ab-4e42-99e6-9183c44e365e">
> bro do i need to buy subscription to use the feature?
> 

Well if you want to use the current account then yes. If you want you can create a different account but the catch is for creating API key they will ask for phone number verification so if you have extra numbers you can use them to create api keys.

**Comment by ItsAnkitPatel** [comment]
> yes i m using my own api that all i did and prompt was made using that surprise me button 
> 

Then most likely your api key is expired.

**Comment by ItsAnkitPatel** [comment]
> > I am also facing same ptoblem
> 
> Can you share your code repo?

@Rutuja1427 are you still facing the issue if yes then you can ask @Archana2806 for her help too.. Her project issue is resolved..
She can help you..

**Comment by Rutuja1427** [comment]
@Archana2806 can you help me i am facing error while fetch an api

**Comment by Rutuja1427** [comment]
![Screenshot (12)](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/147986450/8ec37552-fffd-4a45-add4-2614e96226b3)
API limit reached this error but there is no usage

**Comment by Rutuja1427** [comment]
![Screenshot (13)](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/147986450/ef2dcc5e-e24b-4177-b383-8613f8692cb8)
@ItsAnkitPatel

**Comment by ItsAnkitPatel** [comment]
> ![Screenshot (13)](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/147986450/ef2dcc5e-e24b-4177-b383-8613f8692cb8)
> @ItsAnkitPatel 

Is this my project ?
If yes then it won't work bcs my backend is hosted on a different server whose url is not given bcs of security reasons. So you have to run(host) the server on your machine too..

And that API limit reached is just a custom msg. I will configure it in a better way to give better error information.

Let me know if there are other issues.
And also can you upload your code on github? so that I can run it on my machine for faster debugging.

You can also message me on discord username: ankit_patel

**Comment by Archana2806** [comment]
@Rutuja1427  Have u received free credits from OpenAI or have you paid to get any! if yes there might be some issue with the environment variable or code. if no you got to get credits for image generation.

**Comment by ItsAnkitPatel** [comment]
> ![Screenshot (12)](https://private-user-images.githubusercontent.com/147986450/321950392-8ec37552-fffd-4a45-add4-2614e96226b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjkwNTgsIm5iZiI6MTcxMjkyODc1OCwicGF0aCI6Ii8xNDc5ODY0NTAvMzIxOTUwMzkyLThlYzM3NTUyLWZmZmQtNGE0NS1hZGQ0LTI2MTRlOTYyMjZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxMzMyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmU0MzkxMzI4YWEzM2I2ZmQ1NmQ5OTEwYTQ5OTVmMjJlN2Q4MzU4MGRkYWYzNzllNDI5MWM2ZjZlNThiMzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvkmMBWVSaZ3XGY9rzXB6I4SpjAMx5H7iRgYKvRY7GI) API limit reached this error but there is no usage

@Archana2806 was right.. @Rutuja1427  you don't have any credits from openai.. first generate the api key then you will see usd grants in your account..

This is how my account look like.. on the right side you can see the info ? That's how it will look like if you have credits..

![image](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/163109788/dedf3af8-0252-4137-8a57-890bd148ea46)

**Comment by akshay2245** [comment]
I tried using different mobile no. which i haven't used before but its showing that its used for another account.

**Comment by ItsAnkitPatel** [comment]
> I tried using different mobile no. which i haven't used before but its showing that its used for another account.

Someone(frined/family member) who is into openai API may be used your number ? I don't know what might be other reason if you are using a new number.. it should work but I don't know the solution of this either.. sorry.

**Comment by akshay2245** [comment]
No its fine,And One more thing how did you uploaded it on vercel can u tell me the procedure??

**Comment by akshay2245** [comment]
do i have create build folder then navigate it to backend ??

**Comment by ItsAnkitPatel** [comment]
> No its fine,And One more thing how did you uploaded it on vercel can u tell me the procedure??
> 

Well YT video is enough. I also got to know from there too. Vercel will ask for repo access. Internally it runs the `npm build` so you don't need to do it.
Hosting fronted is easy in Vercel. When it comes to hosting backend it's quite tricky in Vercel (**render** is easy to use in this case)
Just directly upload the project on GitHub repo that's enough and give access to the Vercel (node modules upload not important)

(And one suggestion.. you can edit your messages.. so posting mutiple messages is not a good idea)

**Comment by akshay2245** [comment]
Oh oKay Thanks Alot Brother!!

**Comment by akshay2245** [comment]
<img width="1470" alt="Screenshot 2024-04-17 at 11 48 47 PM" src="https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/83343001/0adfba57-07d8-47dc-8212-bfe8d021d4a9">
bro i m getting the above errors after uploading!
i want to know what all chnages you did while uploading and how did you navigated it to client -fronted

**Comment by akshay2245** [comment]
<img width="1470" alt="Screenshot 2024-04-18 at 12 10 39 AM" src="https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/83343001/c25d96c0-8761-4e58-8c8b-d52dfd5614fc">
now the backend is working but how to display the frontend

**Comment by ItsAnkitPatel** [comment]
> <img alt="Screenshot 2024-04-17 at 11 48 47 PM" width="1470" src="https://private-user-images.githubusercontent.com/83343001/323335647-0adfba57-07d8-47dc-8212-bfe8d021d4a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQzMTcsIm5iZiI6MTcxMzQyNDAxNywicGF0aCI6Ii84MzM0MzAwMS8zMjMzMzU2NDctMGFkZmJhNTctMDdkOC00N2RjLTgyMTItYmZlOGQwMjFkNGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDlkNjk3N2I0ZGExZjBmNzYxNGVkZjJhY2ZjZmZlZWE0MzA0ZjAwM2VmMTNhYjJlYWU2YjEyM2ZlMGNiYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dozV1JDS-HrUk2W0mrzks7V2-t4_VIC0KDc2Gf6_nq4"> bro i m getting the above errors after uploading! i want to know what all chnages you did while uploading and how did you navigated it to client -fronted

Hmm.. first thing when you were uploading did you choose the directory in Vercel for this project ? It will be `./client` for this project.. try to check this part... bcs if this part is not set Vercel will run the `npm run build` on root and as you know there is only client and server folder on the root no `veet` configuration at all..

![image](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/163109788/42e6628a-8048-4d11-8dc9-fd6c6907827d)


First change the root directory to `client` if you still face errors after this just msg me on discord(username: ankit_patel) we will together figure out

**Comment by ItsAnkitPatel** [comment]
> <img alt="Screenshot 2024-04-18 at 12 10 39 AM" width="1470" src="https://private-user-images.githubusercontent.com/83343001/323341933-c25d96c0-8761-4e58-8c8b-d52dfd5614fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQzMTcsIm5iZiI6MTcxMzQyNDAxNywicGF0aCI6Ii84MzM0MzAwMS8zMjMzNDE5MzMtYzI1ZDk2YzAtODc2MS00ZTU4LThjOGItZDUyZGZkNTYxNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOTQxZTEwZTA3YmEzYTUzY2U0Mjk4YTk5NzU0NmE3NzcwYTEwMTEzOGNiZDVhMjk2YjNlMjIxOGQ4ZjIyNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fG2_kSrfOvQoYY1jnKfAr55SGSyefspRyMp2qps6qxs"> now the backend is working but how to display the frontend

After doing the correction in root directory just add your render server link inside environment section of Vercel and it will work... if it doesn't let me know via discord (for faster communication)

**Comment by deep55gariya** [comment]
![Screenshot 2024-04-18 182257](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/97430393/7557c5f7-04c8-4a0d-a0ed-c100363b1b7c)
can anyone help me to solve this

**Comment by ItsAnkitPatel** [comment]
@deep55gariya can you also share the browser console output to see the more descriptive error..?
Is your code available on github ?

**Comment by akshay2245** [comment]
> ankit_patel

bro i have sent you friend request in discord.Cient is working and you told me to add some link in environment variable right can u explain me that??

**Comment by ItsAnkitPatel** [comment]
> > ankit_patel
> 
> bro i have sent you friend request in discord.Cient is working and you told me to add some link in environment variable right can u explain me that??
> 

Ok.. for env you have to add on client and server both
