### ISSUE TITLE
Failed to fetch error

### ISSUE THREAD

**Issue by Eyepatch2109** [adrianhajdin/project_ai_mern_image_generation#76]
![Screenshot 2024-05-08 192307](https://github.com/adrianhajdin/project_ai_mern_image_generation/assets/155938890/e6380446-a96e-4c2a-9fcc-f2e473bb17b9)

I have also made changes to the dalleRoutes.js and also have credits... still am getting this error

**Comment by jatinsharma2040** [comment]
Did you get any solution regarding this problem.
![Screenshot (107)](https://github.com/user-attachments/assets/7a87fde0-65a9-4c85-9809-24207de3fe3a)
